# Generated by Django 2.2.2 on 2019-06-16 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, upload_to='')),
                ('company_name', models.CharField(max_length=150)),
                ('company_problem_statement', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement_1', models.CharField(max_length=300)),
                ('abstract_1', models.TextField(default='')),
                ('problem_statement_2', models.CharField(max_length=300)),
                ('abstract_2', models.TextField(default='')),
                ('problem_statement_3', models.CharField(max_length=300)),
                ('abstract_3', models.TextField(default='')),
                ('problem_statement_4', models.CharField(max_length=300)),
                ('abstract_4', models.TextField(default='')),
                ('team_name', models.CharField(max_length=150)),
                ('team_leader_name', models.CharField(max_length=150)),
                ('team_leader_college_name', models.CharField(max_length=150)),
                ('team_leader_city', models.CharField(max_length=150)),
                ('team_leader_email', models.EmailField(max_length=150)),
                ('team_leader_tel_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Number.', regex='^\\+?1?\\d{9,15}$')])),
                ('team_leader_tsize', models.CharField(choices=[('S', 'S-36'), ('M', 'M-38'), ('L', 'L-40'), ('XL', 'XL-42'), ('XXL', 'XXL-44')], default='S', max_length=5, verbose_name='T-SHIRT')),
                ('teammate1_name', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate1_college_name', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate1_city', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate1_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('teammate1_tel_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Number.', regex='^\\+?1?\\d{9,15}$')])),
                ('teammate1_tsize', models.CharField(blank=True, choices=[('S', 'S-36'), ('M', 'M-38'), ('L', 'L-40'), ('XL', 'XL-42'), ('XXL', 'XXL-44')], default='S', max_length=5, null=True, verbose_name='T-SHIRT')),
                ('teammate2_name', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate2_college_name', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate2_city', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate2_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('teammate2_tel_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Number.', regex='^\\+?1?\\d{9,15}$')])),
                ('teammate2_tsize', models.CharField(blank=True, choices=[('S', 'S-36'), ('M', 'M-38'), ('L', 'L-40'), ('XL', 'XL-42'), ('XXL', 'XXL-44')], default='S', max_length=5, null=True, verbose_name='T-SHIRT')),
                ('teammate3_name', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate3_college_name', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate3_city', models.CharField(blank=True, max_length=150, null=True)),
                ('teammate3_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('teammate3_tel_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Number.', regex='^\\+?1?\\d{9,15}$')])),
                ('teammate3_tsize', models.CharField(blank=True, choices=[('S', 'S-36'), ('M', 'M-38'), ('L', 'L-40'), ('XL', 'XL-42'), ('XXL', 'XXL-44')], default='S', max_length=5, null=True, verbose_name='T-SHIRT')),
            ],
            options={
                'verbose_name': 'Student_Form',
            },
        ),
    ]
