# Generated by Django 2.2.2 on 2019-06-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='team_leader_city',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='teammate1_city',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='teammate2_city',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='teammate3_city',
        ),
        migrations.AddField(
            model_name='studentform',
            name='team_leader_year',
            field=models.CharField(blank=True, choices=[('I', 'First Year'), ('II', 'Second Year'), ('III', 'Third Year'), ('IV', 'Fourth Year')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='teammate1_year',
            field=models.CharField(blank=True, choices=[('I', 'First Year'), ('II', 'Second Year'), ('III', 'Third Year'), ('IV', 'Fourth Year')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='teammate2_year',
            field=models.CharField(blank=True, choices=[('I', 'First Year'), ('II', 'Second Year'), ('III', 'Third Year'), ('IV', 'Fourth Year')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='teammate3_year',
            field=models.CharField(blank=True, choices=[('I', 'First Year'), ('II', 'Second Year'), ('III', 'Third Year'), ('IV', 'Fourth Year')], max_length=10, null=True),
        ),
    ]
