# Generated by Django 2.2.3 on 2019-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190616_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='team_leader_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=5, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='teammate1_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=5, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='teammate2_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=5, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='teammate3_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=5, verbose_name='Gender'),
        ),
    ]
